version: "3.8"

services:
  website:
    image: nginx
    volumes:
      - ./public:/usr/share/nginx/html
    ports:
      - "8100:80"
    environment:
      - VIRTUAL_HOST=twigcodes.com
      - LETSENCRYPT_HOST=twigcodes.com
      - VIRTUAL_PORT=8100
    networks:
      - local
      - default

networks:
  local:
    driver: bridge
  default:
    name: proxy
