version: "3.8"

services:
  website:
    image: nginx
    volumes:
      - ./public:/usr/share/nginx/html
      - ./.well-known:/usr/share/nginx/html/.well-known
    ports:
      - "8100:80"
    environment:
      - VIRTUAL_HOST=twigcodes.com
      - LETSENCRYPT_HOST=twigcodes.com
    networks:
      - proxy

networks:
  proxy:
    external: true
